version: "3"

networks:
  xcap:
    external:
      name: igaku

igaku-frontend:
    image: igaku-frontend:1.0
    build:
      dockerfile: dev.Dockerfile
      context: ./
    volumes:
      - "./:/app"
      - /app/node_modules
    ports:
      - "3000:3000"
    networks: 
      - igaku