export const ASYNC_LOG_USER = 'ASYNC_LOG_USER';
export const ASYNC_FETCH_CURRENT_USER_DATA = 'ASYNC_FETCH_CURRENT_USER_DATA';
export const ASYNC_SIGNUP = 'ASYNC_SIGNUP';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_ERROR = 'SET_ERROR';
