export const clinicConstants = {
    CLINIC_CATEGORIES: [
        'GP',
        'Psychology'
    ],
    CLINIC_PROVIDERS: [
        'AIA',
        'AVIVA'
    ],
    BOOKING_STATUS:{
        PENDING: 'pending',
        ACCEPTED: 'accepted',
        REJECTED: 'rejected'
    },
    DEFAULT_CLINIC_OPENING_TIMES:[
        "8:30", "17:30"
    ],
    LOADING_CLINIC: 'LOADING_CLINIC',
    SAVING_CLINIC: 'SAVING_CLINIC',
    GET_ADMIN_PROFILE: 'GET_ADMIN_PROFILE',
    GET_CLINIC: 'GET_CLINIC',
    ADD_CLINIC: 'ADD_CLINIC',
    EDIT_CLINIC: 'EDIT_CLINIC',
    LOADING_CLINIC_PRACTITIONERS: 'LOADING_CLINIC_PRACTITIONERS',
    LOADING_PRACTITIONERS_FOR_CLINIC: 'LOADING_PRACTITIONERS_FOR_CLINIC',
    GET_ALL_PRACTITIONERS: 'GET_ALL_PRACTITIONERS',
    GET_CLINIC_PRACTITIONERS: 'GET_CLINIC_PRACTITIONERS',
    ADD_PRACTITIONER: 'ADD_PRACTITIONER',
    DELETE_PRACTITIONER: 'DELETE_PRACTITIONER',
    LOADING_CLINIC_PATIENTS: 'LOADING_CLINIC_PATIENTS',
    GET_CLINIC_PATIENTS: 'GET_CLINIC_PATIENTS',
    LOADING_CLINIC_PRACTITIONERS_WITH_BOOKINGS: 'LOADING_CLINIC_PRACTITIONERS_WITH_BOOKINGS',
    GET_CLINIC_PRACTITIONERS_WITH_BOOKINGS: 'GET_CLINIC_PRACTITIONERS_WITH_BOOKINGS',
    LOADING_CLINIC_PRACTITIONERS_BOOKINGS: 'LOADING_CLINIC_PRACTITIONERS_BOOKINGS',
    EDIT_CLINIC_BOOKING_STATUS: 'EDIT_CLINIC_BOOKING_STATUS',
    LOADING_CLINIC_OPENING_HOURS: 'LOADING_CLINIC_OPENING_HOURS',
    GET_CLINIC_OPENING_HOURS: 'GET_CLINIC_OPENING_HOURS',
    DELETE_CLINIC_OPENING_HOUR: 'DELETE_CLINIC_OPENING_HOUR',
    ADD_CLINIC_OPENING_HOURS: 'ADD_CLINIC_OPENING_HOURS',
    EDIT_CLINIC_OPENING_HOUR: 'EDIT_CLINIC_OPENING_HOUR'
}