export const clinicConstants = {
    LOADING_CLINIC: 'LOADING_CLINIC',
    GET_ADMIN_PROFILE: 'GET_ADMIN_PROFILE',
    GET_ADMIN_PROFILE_SUCCESS: 'GET_ADMIN_PROFILE_SUCCESS',
    GET_ADMIN_PROFILE_ERROR: 'GET_ADMIN_PROFILE_ERROR',
    GET_CLINIC_SUCCESS: 'GET_CLINIC_SUCCESS',
    GET_CLINIC_ERROR: 'GET_CLINIC_ERROR',
    NO_CLINIC_FOUND: 'NO_CLINIC_FOUND',
    GET_ALL_PRACTITIONERS: 'GET_ALL_PRACTITIONERS',
    GET_CLINIC_PRACTITIONERS: 'GET_CLINIC_PRACTITIONERS',
    ADD_PRACTITIONER: 'ADD_PRACTITIONER',
    DELETE_PRACTITIONER: 'DELETE_PRACTITIONER',
}