export const clinicConstants = {
    LOADING_CLINIC: 'LOADING_CLINIC',
    GET_ADMIN_PROFILE: 'GET_ADMIN_PROFILE',
    GET_CLINIC: 'GET_CLINIC',
    NO_CLINIC_FOUND: 'NO_CLINIC_FOUND',
    LOADING_CLINIC_PRACTITIONERS: 'LOADING_CLINIC_PRACTITIONERS',
    GET_ALL_PRACTITIONERS: 'GET_ALL_PRACTITIONERS',
    GET_CLINIC_PRACTITIONERS: 'GET_CLINIC_PRACTITIONERS',
    ADD_PRACTITIONER: 'ADD_PRACTITIONER',
    DELETE_PRACTITIONER: 'DELETE_PRACTITIONER',
}